# Generated by Django 5.2.7 on 2025-11-02 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('coefficients', '0001_initial'),
        ('forms', '0001_initial'),
        ('geo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_date', models.DateTimeField(blank=True, null=True, verbose_name='Плановая дата')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания')),
                ('status', models.CharField(choices=[('planned', 'Запланирован'), ('in_progress', 'В процессе'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='planned', max_length=20, verbose_name='Статус')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарии')),
                ('form_data', models.JSONField(blank=True, default=dict, verbose_name='Данные формы')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='Подпись')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='geo.outlet', verbose_name='Точка сбыта')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Визит',
                'verbose_name_plural': 'Визиты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_numeric', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Числовое значение')),
                ('value_text', models.TextField(blank=True, verbose_name='Текстовое значение')),
                ('value_boolean', models.BooleanField(blank=True, null=True, verbose_name='Да/Нет значение')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарии')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Метаданные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('coefficient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='coefficients.coefficient', verbose_name='Коэффициент')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='catalog.product', verbose_name='Товар')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='visits.visit', verbose_name='Визит')),
            ],
            options={
                'verbose_name': 'Наблюдение',
                'verbose_name_plural': 'Наблюдения',
                'ordering': ['visit', 'coefficient'],
            },
        ),
        migrations.CreateModel(
            name='VisitMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('photo', 'Фото'), ('video', 'Видео'), ('audio', 'Аудио'), ('document', 'Документ')], default='photo', max_length=20, verbose_name='Тип медиа')),
                ('file', models.FileField(upload_to='visit_media/%Y/%m/%d/', verbose_name='Файл')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='visit_media/thumbnails/', verbose_name='Миниатюра')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('exif_data', models.JSONField(blank=True, default=dict, verbose_name='EXIF данные')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='visits.observation', verbose_name='Наблюдение')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='visits.visit', verbose_name='Визит')),
            ],
            options={
                'verbose_name': 'Медиа файл визита',
                'verbose_name_plural': 'Медиа файлы визитов',
                'ordering': ['visit', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('type', models.CharField(choices=[('monitoring', 'Мониторинг'), ('audit', 'Аудит'), ('survey', 'Опрос'), ('inspection', 'Инспекция'), ('other', 'Другое')], default='monitoring', max_length=50, verbose_name='Тип')),
                ('requires_photo', models.BooleanField(default=False, verbose_name='Требует фото')),
                ('requires_signature', models.BooleanField(default=False, verbose_name='Требует подпись')),
                ('requires_gps', models.BooleanField(default=False, verbose_name='Требует GPS координаты')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные настройки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('coefficients', models.ManyToManyField(blank=True, related_name='visit_types', to='coefficients.coefficient', verbose_name='Коэффициенты')),
                ('form_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_types', to='forms.formtemplate', verbose_name='Шаблон формы')),
            ],
            options={
                'verbose_name': 'Тип визита',
                'verbose_name_plural': 'Типы визитов',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='visit',
            name='visit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='visits.visittype', verbose_name='Тип визита'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['visit', 'coefficient'], name='visits_obse_visit_i_560661_idx'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['coefficient', 'product'], name='visits_obse_coeffic_8900b0_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['outlet', '-created_at'], name='visits_visi_outlet__c19dc2_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['user', '-created_at'], name='visits_visi_user_id_766967_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['status'], name='visits_visi_status_ae8d13_idx'),
        ),
    ]
