# Generated by Django 5.2.7 on 2025-11-22 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_attributegroup_attributedefinition_and_more'),
        ('geo', '0002_display_footfallcounter_displayinventory_and_more'),
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за единицу')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('sale_date', models.DateTimeField(verbose_name='Дата продажи')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='Зафиксировано')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='geo.outlet', verbose_name='Торговая точка')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='catalog.product', verbose_name='Товар')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Зафиксировал')),
            ],
            options={
                'verbose_name': 'Продажа',
                'verbose_name_plural': 'Продажи',
                'ordering': ['-sale_date'],
            },
        ),
    ]
