# Generated by Django 5.2.7 on 2025-11-29 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='data_source_type',
            field=models.CharField(choices=[('MON', 'Мониторинговые'), ('EXP', 'Экспертные'), ('AI', 'Данные ИИ')], default='MON', help_text='Как получено это наблюдение: замер, от эксперта или ИИ', max_length=10, verbose_name='Тип источника данных'),
        ),
        migrations.AddField(
            model_name='visit',
            name='data_source_type',
            field=models.CharField(choices=[('MON', 'Мониторинговые'), ('EXP', 'Экспертные'), ('AI', 'Данные ИИ')], default='MON', help_text='Тип визита: мониторинговый (замеры) или экспертный (интервью)', max_length=10, verbose_name='Тип визита'),
        ),
    ]
