# Generated by Django 5.2.7 on 2025-11-02 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coefficient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('data_type', models.CharField(choices=[('MON', 'Мониторинговые'), ('EXP', 'Экспертные'), ('Mixed', 'Смешанные')], default='MON', max_length=10, verbose_name='Тип данных')),
                ('applies_to_outlet', models.BooleanField(default=True, verbose_name='Применяется к точке')),
                ('applies_to_channel', models.BooleanField(default=False, verbose_name='Применяется к каналу')),
                ('applies_to_region', models.BooleanField(default=False, verbose_name='Применяется к региону')),
                ('applies_to_country', models.BooleanField(default=False, verbose_name='Применяется к стране')),
                ('applies_to_global', models.BooleanField(default=False, verbose_name='Применяется к глобальному рынку')),
                ('value_type', models.CharField(choices=[('numeric', 'Числовое'), ('text', 'Текстовое'), ('boolean', 'Да/Нет')], default='numeric', max_length=20, verbose_name='Тип значения')),
                ('unit', models.CharField(blank=True, help_text='Например: штук, кг, %', max_length=50, verbose_name='Единица измерения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные настройки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Коэффициент',
                'verbose_name_plural': 'Коэффициенты',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='coefficient_code_9cec01_idx'), models.Index(fields=['data_type'], name='coefficient_data_ty_fef61d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('expression', models.TextField(help_text='Формула расчета, например: (C1 + C2) / C3 * 100', verbose_name='Выражение')),
                ('result_type', models.CharField(choices=[('numeric', 'Числовое'), ('percentage', 'Процент'), ('boolean', 'Да/Нет')], default='numeric', max_length=20, verbose_name='Тип результата')),
                ('result_unit', models.CharField(blank=True, max_length=50, verbose_name='Единица измерения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные настройки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('coefficients', models.ManyToManyField(blank=True, related_name='formulas', to='coefficients.coefficient', verbose_name='Коэффициенты')),
            ],
            options={
                'verbose_name': 'Формула',
                'verbose_name_plural': 'Формулы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('category', models.CharField(choices=[('distribution', 'Дистрибуция'), ('price', 'Цена'), ('share', 'Доля рынка'), ('availability', 'Наличие'), ('other', 'Другое')], default='other', max_length=50, verbose_name='Категория')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные настройки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('coefficients', models.ManyToManyField(blank=True, related_name='metrics', to='coefficients.coefficient', verbose_name='Коэффициенты')),
                ('formula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metrics', to='coefficients.formula', verbose_name='Формула расчета')),
            ],
            options={
                'verbose_name': 'Метрика',
                'verbose_name_plural': 'Метрики',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('rule_type', models.CharField(choices=[('aggregation', 'Агрегация'), ('validation', 'Валидация'), ('transformation', 'Трансформация')], default='aggregation', max_length=50, verbose_name='Тип правила')),
                ('aggregation_method', models.CharField(blank=True, choices=[('sum', 'Сумма'), ('avg', 'Среднее'), ('min', 'Минимум'), ('max', 'Максимум'), ('count', 'Количество')], max_length=20, null=True, verbose_name='Метод агрегации')),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Дополнительные параметры правила', verbose_name='Параметры')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('applies_to', models.ManyToManyField(blank=True, related_name='rules', to='coefficients.coefficient', verbose_name='Применяется к коэффициентам')),
            ],
            options={
                'verbose_name': 'Правило',
                'verbose_name_plural': 'Правила',
                'ordering': ['rule_type', 'name'],
            },
        ),
    ]
