# Generated by Django 5.2.7 on 2025-11-29 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coefficients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='source_data_type',
            field=models.CharField(choices=[('MON', 'Мониторинговые'), ('EXP', 'Экспертные'), ('AI', 'Данные ИИ'), ('CUSTOM', 'Смешанные (Custom)')], default='MON', help_text='Какой тип данных использовать для расчета: мониторинговые, экспертные, ИИ или смешанные (custom)', max_length=10, verbose_name='Тип источника данных для расчета'),
        ),
        migrations.AlterField(
            model_name='coefficient',
            name='data_type',
            field=models.CharField(choices=[('MON', 'Мониторинговые'), ('EXP', 'Экспертные'), ('AI', 'Данные ИИ')], default='MON', help_text='Источник данных для коэффициента', max_length=10, verbose_name='Тип источника данных'),
        ),
    ]
