# Generated by Django 5.2.7 on 2025-11-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coefficients', '0002_formula_source_data_type_alter_coefficient_data_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='source_data_type',
            field=models.CharField(choices=[('MON', 'Мониторинговые'), ('EXP', 'Экспертные'), ('AI', 'Данные ИИ'), ('CUSTOM', 'Смешанные (Custom)')], default='MON', help_text='Какой тип данных использовать для расчета метрики: мониторинговые, экспертные, ИИ или смешанные (custom)', max_length=10, verbose_name='Тип источника данных'),
        ),
    ]
