# Generated by Django 5.2.7 on 2025-11-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('form_type', models.CharField(choices=[('visit', 'Визит'), ('survey', 'Опрос'), ('audit', 'Аудит'), ('report', 'Отчет'), ('other', 'Другое')], default='visit', max_length=50, verbose_name='Тип формы')),
                ('fields_schema', models.JSONField(blank=True, default=list, help_text='JSON описание полей формы', verbose_name='Схема полей')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Категория')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='Версия')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активен'), ('archived', 'Архивирован')], default='draft', max_length=20, verbose_name='Статус')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные настройки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('applies_to_channels', models.ManyToManyField(blank=True, related_name='form_templates', to='geo.channel', verbose_name='Применяется к каналам')),
            ],
            options={
                'verbose_name': 'Шаблон формы',
                'verbose_name_plural': 'Шаблоны форм',
                'ordering': ['name'],
            },
        ),
    ]
