# Generated by Django 5.2.7 on 2025-11-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Создание'), ('update', 'Обновление'), ('delete', 'Удаление')], max_length=20, verbose_name='Действие')),
                ('table_name', models.CharField(max_length=100, verbose_name='Таблица')),
                ('record_id', models.PositiveIntegerField(verbose_name='ID записи')),
                ('old_value', models.JSONField(blank=True, null=True, verbose_name='Старое значение')),
                ('new_value', models.JSONField(blank=True, null=True, verbose_name='Новое значение')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
            ],
            options={
                'verbose_name': 'Запись аудита',
                'verbose_name_plural': 'Журнал аудита',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('type', models.CharField(choices=[('1c', '1C'), ('excel', 'Excel'), ('crm', 'CRM'), ('google_sheets', 'Google Sheets'), ('api', 'API')], max_length=50, verbose_name='Тип')),
                ('api_key', models.CharField(blank=True, max_length=500, verbose_name='API ключ')),
                ('endpoint_url', models.URLField(blank=True, verbose_name='URL endpoint')),
                ('auth_params', models.JSONField(blank=True, default=dict, verbose_name='Параметры авторизации')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Настройки интеграции',
                'verbose_name_plural': 'Настройки интеграций',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Информация'), ('warning', 'Предупреждение'), ('error', 'Ошибка'), ('critical', 'Критическая ошибка')], default='info', max_length=20, verbose_name='Уровень')),
                ('action_type', models.CharField(max_length=100, verbose_name='Тип действия')),
                ('description', models.TextField(verbose_name='Описание')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Системный лог',
                'verbose_name_plural': 'Системные логи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Datum', max_length=255, verbose_name='Название системы')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='system/', verbose_name='Логотип')),
                ('currency', models.CharField(default='USD', max_length=10, verbose_name='Валюта по умолчанию')),
                ('language', models.CharField(default='ru', max_length=10, verbose_name='Язык')),
                ('timezone', models.CharField(default='Asia/Tashkent', max_length=50, verbose_name='Часовой пояс')),
                ('unit_system', models.CharField(choices=[('metric', 'Метрическая'), ('imperial', 'Имперская')], default='metric', max_length=20, verbose_name='Система единиц')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Настройки системы',
                'verbose_name_plural': 'Настройки системы',
            },
        ),
    ]
