# Generated by Django 5.2.7 on 2025-11-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('dashboard_type', models.CharField(choices=[('overview', 'Обзорный'), ('distribution', 'Дистрибуция'), ('sales', 'Продажи'), ('custom', 'Пользовательский')], default='overview', max_length=50, verbose_name='Тип')),
                ('widgets_config', models.JSONField(blank=True, default=list, verbose_name='Конфигурация виджетов')),
                ('default_filters', models.JSONField(blank=True, default=dict, verbose_name='Фильтры по умолчанию')),
                ('refresh_interval', models.PositiveIntegerField(default=15, verbose_name='Интервал обновления (мин)')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичный')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Дашборд',
                'verbose_name_plural': 'Дашборды',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FilterPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('applies_to', models.CharField(choices=[('dashboard', 'Дашборд'), ('report', 'Отчет'), ('visit', 'Визит'), ('product', 'Товар')], default='dashboard', max_length=50, verbose_name='Применяется к')),
                ('filters', models.JSONField(default=dict, verbose_name='Фильтры')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Набор фильтров',
                'verbose_name_plural': 'Наборы фильтров',
                'ordering': ['owner', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ForecastModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('model_type', models.CharField(choices=[('linear', 'Линейная'), ('exponential', 'Экспоненциальная'), ('seasonal', 'Сезонная'), ('arima', 'ARIMA'), ('custom', 'Пользовательская')], default='linear', max_length=50, verbose_name='Тип модели')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='Параметры')),
                ('training_data', models.JSONField(blank=True, default=dict, verbose_name='Данные обучения')),
                ('training_score', models.FloatField(blank=True, null=True, verbose_name='Точность модели')),
                ('forecast_horizon', models.PositiveIntegerField(default=30, verbose_name='Горизонт прогноза (дней)')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('training', 'Обучение'), ('active', 'Активна'), ('archived', 'Архивирована')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('trained_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата обучения')),
            ],
            options={
                'verbose_name': 'Модель прогнозирования',
                'verbose_name_plural': 'Модели прогнозирования',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='Дата с')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Дата по')),
                ('filters', models.JSONField(blank=True, default=dict, verbose_name='Фильтры')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Данные')),
                ('format', models.CharField(choices=[('html', 'HTML'), ('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], default='html', max_length=20, verbose_name='Формат')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/', verbose_name='Файл')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('processing', 'Обработка'), ('completed', 'Завершен'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата генерации')),
                ('generation_time', models.FloatField(blank=True, null=True, verbose_name='Время генерации (сек)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('report_type', models.CharField(choices=[('summary', 'Сводный'), ('detailed', 'Детальный'), ('comparison', 'Сравнительный'), ('trend', 'Трендовый'), ('custom', 'Пользовательский')], default='summary', max_length=50, verbose_name='Тип отчета')),
                ('category', models.CharField(choices=[('distribution', 'Дистрибуция'), ('sales', 'Продажи'), ('visits', 'Визиты'), ('products', 'Товары'), ('other', 'Другое')], default='other', max_length=50, verbose_name='Категория')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Структура и параметры отчета', verbose_name='Конфигурация')),
                ('sql_query', models.TextField(blank=True, verbose_name='SQL запрос')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Шаблон отчета',
                'verbose_name_plural': 'Шаблоны отчетов',
                'ordering': ['category', 'name'],
            },
        ),
    ]
