# Generated by Django 5.2.7 on 2025-12-04 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='level',
            field=models.CharField(blank=True, choices=[('country', 'Страна'), ('region', 'Регион'), ('channel', 'Канал сбыта'), ('outlet', 'Торговая точка')], max_length=50, null=True, verbose_name='Уровень иерархии'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='level_icon',
            field=models.CharField(blank=True, help_text='Эмодзи для отображения в переключателе', max_length=10, verbose_name='Иконка уровня'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='level_order',
            field=models.PositiveIntegerField(default=0, help_text='Порядок отображения в переключателе', verbose_name='Порядок уровня'),
        ),
    ]
