# Generated by Django 5.2.7 on 2025-12-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_dashboard_level_dashboard_level_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='level',
            field=models.CharField(blank=True, choices=[('country', 'Страна'), ('region', 'Регион'), ('city', 'Город'), ('district', 'Район'), ('channel', 'Канал сбыта'), ('outlet', 'Торговая точка')], max_length=50, null=True, verbose_name='Уровень иерархии'),
        ),
    ]
