# Generated by Django 5.2.7 on 2025-11-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('backup_type', models.CharField(choices=[('full', 'Полный'), ('incremental', 'Инкрементный'), ('differential', 'Дифференциальный'), ('manual', 'Ручной')], default='full', max_length=50, verbose_name='Тип бэкапа')),
                ('includes_database', models.BooleanField(default=True, verbose_name='База данных')),
                ('includes_media', models.BooleanField(default=False, verbose_name='Медиа файлы')),
                ('includes_settings', models.BooleanField(default=True, verbose_name='Настройки')),
                ('file', models.FileField(blank=True, null=True, upload_to='backups/%Y/%m/', verbose_name='Файл бэкапа')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='Размер файла (байт)')),
                ('checksum', models.CharField(blank=True, max_length=64, verbose_name='Контрольная сумма')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Информация о содержимом бэкапа', verbose_name='Метаданные')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('in_progress', 'Выполняется'), ('completed', 'Завершен'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='Длительность (сек)')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Срок хранения до')),
                ('is_restored', models.BooleanField(default=False, verbose_name='Восстановлен')),
                ('restored_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата восстановления')),
                ('error_log', models.TextField(blank=True, verbose_name='Лог ошибок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Резервная копия',
                'verbose_name_plural': 'Резервные копии',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('data_type', models.CharField(choices=[('outlets', 'Точки сбыта'), ('products', 'Товары'), ('visits', 'Визиты'), ('observations', 'Наблюдения'), ('report', 'Отчет'), ('dashboard', 'Дашборд')], default='outlets', max_length=50, verbose_name='Тип данных')),
                ('export_format', models.CharField(choices=[('csv', 'CSV'), ('excel', 'Excel'), ('json', 'JSON'), ('xml', 'XML'), ('pdf', 'PDF')], default='excel', max_length=20, verbose_name='Формат экспорта')),
                ('filters', models.JSONField(blank=True, default=dict, verbose_name='Фильтры')),
                ('options', models.JSONField(blank=True, default=dict, help_text='Настройки формата, колонок и т.д.', verbose_name='Опции экспорта')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('processing', 'Обработка'), ('completed', 'Завершен'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('file', models.FileField(blank=True, null=True, upload_to='exports/%Y/%m/', verbose_name='Файл результата')),
                ('total_records', models.PositiveIntegerField(default=0, verbose_name='Всего записей')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Размер файла (байт)')),
                ('error_log', models.TextField(blank=True, verbose_name='Лог ошибок')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='Длительность (сек)')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Срок хранения до')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Задание экспорта',
                'verbose_name_plural': 'Задания экспорта',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('source_type', models.CharField(choices=[('file', 'Файл'), ('api', 'API'), ('database', 'База данных'), ('1c', '1C'), ('google_sheets', 'Google Sheets')], default='file', max_length=50, verbose_name='Тип источника')),
                ('source_file', models.FileField(blank=True, null=True, upload_to='imports/%Y/%m/', verbose_name='Файл источник')),
                ('source_url', models.URLField(blank=True, verbose_name='URL источника')),
                ('data_type', models.CharField(choices=[('outlets', 'Точки сбыта'), ('products', 'Товары'), ('visits', 'Визиты'), ('observations', 'Наблюдения'), ('coefficients', 'Коэффициенты')], default='outlets', max_length=50, verbose_name='Тип данных')),
                ('data_format', models.CharField(choices=[('csv', 'CSV'), ('excel', 'Excel'), ('json', 'JSON'), ('xml', 'XML')], default='csv', max_length=20, verbose_name='Формат данных')),
                ('mapping', models.JSONField(blank=True, default=dict, help_text='Маппинг полей источника на поля модели', verbose_name='Соответствие полей')),
                ('options', models.JSONField(blank=True, default=dict, verbose_name='Опции импорта')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('processing', 'Обработка'), ('completed', 'Завершен'), ('failed', 'Ошибка'), ('partial', 'Частично завершен')], default='pending', max_length=20, verbose_name='Статус')),
                ('total_records', models.PositiveIntegerField(default=0, verbose_name='Всего записей')),
                ('imported_records', models.PositiveIntegerField(default=0, verbose_name='Импортировано')),
                ('failed_records', models.PositiveIntegerField(default=0, verbose_name='Ошибок')),
                ('skipped_records', models.PositiveIntegerField(default=0, verbose_name='Пропущено')),
                ('error_log', models.TextField(blank=True, verbose_name='Лог ошибок')),
                ('error_file', models.FileField(blank=True, null=True, upload_to='imports/errors/', verbose_name='Файл с ошибками')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='Длительность (сек)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Задание импорта',
                'verbose_name_plural': 'Задания импорта',
                'ordering': ['-created_at'],
            },
        ),
    ]
