# Generated by Django 5.2.7 on 2025-11-02 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='backup',
            name='restored_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restored_backups', to=settings.AUTH_USER_MODEL, verbose_name='Восстановил'),
        ),
        migrations.AddField(
            model_name='exportjob',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='importjob',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddIndex(
            model_name='backup',
            index=models.Index(fields=['status'], name='integration_status_59dbe7_idx'),
        ),
        migrations.AddIndex(
            model_name='backup',
            index=models.Index(fields=['backup_type', '-created_at'], name='integration_backup__7c9e11_idx'),
        ),
        migrations.AddIndex(
            model_name='exportjob',
            index=models.Index(fields=['status'], name='integration_status_3874c7_idx'),
        ),
        migrations.AddIndex(
            model_name='exportjob',
            index=models.Index(fields=['created_by', '-created_at'], name='integration_created_024f6a_idx'),
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['status'], name='integration_status_c3a230_idx'),
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['created_by', '-created_at'], name='integration_created_8e9303_idx'),
        ),
    ]
