# Generated by Django 5.2.7 on 2025-11-21 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название группы')),
                ('code', models.SlugField(max_length=100, unique=True, verbose_name='Код группы')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(help_text='К какой категории относится эта группа атрибутов', on_delete=django.db.models.deletion.CASCADE, related_name='attribute_groups', to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Группа атрибутов',
                'verbose_name_plural': 'Группы атрибутов',
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AttributeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название атрибута')),
                ('code', models.SlugField(max_length=100, unique=True, verbose_name='Код атрибута')),
                ('data_type', models.CharField(choices=[('text', 'Текст'), ('integer', 'Целое число'), ('decimal', 'Десятичное число'), ('boolean', 'Да/Нет'), ('date', 'Дата'), ('choice', 'Выбор из списка'), ('multi_choice', 'Множественный выбор'), ('file', 'Файл')], default='text', max_length=20, verbose_name='Тип данных')),
                ('is_required', models.BooleanField(default=False, verbose_name='Обязательный')),
                ('is_filterable', models.BooleanField(default=True, verbose_name='Можно фильтровать')),
                ('is_searchable', models.BooleanField(default=False, verbose_name='Можно искать')),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Минимальное значение')),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Максимальное значение')),
                ('max_length', models.PositiveIntegerField(blank=True, default=255, null=True, verbose_name='Максимальная длина')),
                ('choices', models.JSONField(blank=True, help_text='JSON список вариантов: ["Вариант 1", "Вариант 2"]', null=True, verbose_name='Варианты выбора')),
                ('unit', models.CharField(blank=True, help_text='Например: г, мм, карат, см', max_length=50, verbose_name='Единица измерения')),
                ('placeholder', models.CharField(blank=True, help_text='Подсказка в поле ввода', max_length=200, verbose_name='Плейсхолдер')),
                ('help_text', models.TextField(blank=True, help_text='Подробное описание атрибута', verbose_name='Текст подсказки')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='catalog.attributegroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Определение атрибута',
                'verbose_name_plural': 'Определения атрибутов',
                'ordering': ['group', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CategoryAttributeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=False, verbose_name='Обязательный')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_templates', to='catalog.attributedefinition', verbose_name='Атрибут')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_templates', to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Шаблон атрибута категории',
                'verbose_name_plural': 'Шаблоны атрибутов категорий',
                'ordering': ['category', 'order'],
                'unique_together': {('category', 'attribute')},
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True, null=True, verbose_name='Текстовое значение')),
                ('value_integer', models.IntegerField(blank=True, null=True, verbose_name='Целочисленное значение')),
                ('value_decimal', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Десятичное значение')),
                ('value_boolean', models.BooleanField(blank=True, null=True, verbose_name='Булево значение')),
                ('value_date', models.DateField(blank=True, null=True, verbose_name='Значение даты')),
                ('value_choice', models.CharField(blank=True, max_length=200, null=True, verbose_name='Выбранное значение')),
                ('value_multi_choice', models.JSONField(blank=True, null=True, verbose_name='Множественный выбор')),
                ('value_file', models.FileField(blank=True, null=True, upload_to='product_attributes/', verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='catalog.attributedefinition', verbose_name='Атрибут')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Значение атрибута',
                'verbose_name_plural': 'Значения атрибутов',
                'ordering': ['product', 'attribute__group', 'attribute__order'],
                'unique_together': {('product', 'attribute')},
            },
        ),
    ]
