# Generated by Django 5.2.7 on 2025-11-29 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_attributegroup_attributedefinition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributedefinition',
            name='data_source_type',
            field=models.CharField(choices=[('MON', 'Мониторинговые'), ('EXP', 'Экспертные'), ('AI', 'Данные ИИ')], default='MON', help_text='Тип источника данных для этого атрибута (можно переопределить при заполнении)', max_length=10, verbose_name='Тип источника данных по умолчанию'),
        ),
        migrations.AddField(
            model_name='productattributevalue',
            name='data_source_type',
            field=models.CharField(choices=[('MON', 'Мониторинговые'), ('EXP', 'Экспертные'), ('AI', 'Данные ИИ')], default='MON', help_text='Как было получено это значение: замер, от эксперта или ИИ', max_length=10, verbose_name='Тип источника данных'),
        ),
    ]
