# Generated by Django 5.2.7 on 2025-11-29 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_attributedefinition_data_source_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributedefinition',
            name='data_source_type',
        ),
        migrations.RemoveField(
            model_name='productattributevalue',
            name='data_source_type',
        ),
    ]
