# Generated by Django 5.2.7 on 2025-11-02 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('code', models.CharField(max_length=50, verbose_name='Код')),
                ('type', models.CharField(choices=[('retail', 'Розница'), ('wholesale', 'Опт'), ('online', 'Онлайн'), ('horeca', 'HoReCa'), ('other', 'Другое')], default='retail', max_length=50, verbose_name='Тип канала')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные настройки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Канал сбыта',
                'verbose_name_plural': 'Каналы сбыта',
                'ordering': ['region', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GlobalMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('currency', models.CharField(default='USD', max_length=10, verbose_name='Валюта')),
                ('unit_weight', models.CharField(default='kg', max_length=20, verbose_name='Единица веса')),
                ('data_type', models.CharField(choices=[('expert', 'Экспертный'), ('monitoring', 'Мониторинговый'), ('mixed', 'Смешанный')], default='mixed', max_length=20, verbose_name='Тип данных')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные настройки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Глобальный рынок',
                'verbose_name_plural': 'Глобальные рынки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код')),
                ('iso_code', models.CharField(max_length=3, unique=True, verbose_name='ISO код')),
                ('currency', models.CharField(max_length=10, verbose_name='Валюта')),
                ('flag_image', models.ImageField(blank=True, null=True, upload_to='flags/', verbose_name='Флаг')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные настройки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('global_market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='geo.globalmarket', verbose_name='Глобальный рынок')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='Код')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('contact_person', models.CharField(blank=True, max_length=255, verbose_name='Контактное лицо')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='outlets/', verbose_name='Фото')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('inactive', 'Неактивна'), ('closed', 'Закрыта')], default='active', max_length=20, verbose_name='Статус')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные настройки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlets', to='geo.channel', verbose_name='Канал')),
            ],
            options={
                'verbose_name': 'Точка сбыта',
                'verbose_name_plural': 'Точки сбыта',
                'ordering': ['channel', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('code', models.CharField(max_length=50, verbose_name='Код')),
                ('geo_polygon', models.JSONField(blank=True, null=True, verbose_name='Полигон (GeoJSON)')),
                ('data_type', models.CharField(choices=[('expert', 'Экспертный'), ('monitoring', 'Мониторинговый'), ('mixed', 'Смешанный')], default='mixed', max_length=20, verbose_name='Тип данных')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные настройки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='geo.country', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'ordering': ['country', 'name'],
                'unique_together': {('country', 'code')},
            },
        ),
        migrations.AddField(
            model_name='channel',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='geo.region', verbose_name='Регион'),
        ),
        migrations.AlterUniqueTogether(
            name='channel',
            unique_together={('region', 'code')},
        ),
    ]
