# Generated by Django 5.2.7 on 2025-11-22 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_attributegroup_attributedefinition_and_more'),
        ('geo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('display_type', models.CharField(choices=[('counter', 'Прилавок'), ('showcase', 'Витрина'), ('stand', 'Стенд'), ('wall', 'Стеллаж')], max_length=50, verbose_name='Тип')),
                ('location', models.CharField(blank=True, help_text='Например: У входа, Центр зала', max_length=200, verbose_name='Расположение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='displays', to='geo.outlet', verbose_name='Торговая точка')),
            ],
            options={
                'verbose_name': 'Витрина',
                'verbose_name_plural': 'Витрины',
            },
        ),
        migrations.CreateModel(
            name='FootfallCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Время замера')),
                ('count', models.IntegerField(help_text='За час', verbose_name='Количество людей')),
                ('counted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Подсчитано')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footfall_counts', to='geo.outlet', verbose_name='Торговая точка')),
            ],
            options={
                'verbose_name': 'Проходимость',
                'verbose_name_plural': 'Проходимость',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DisplayInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('position', models.CharField(blank=True, help_text='Например: Верхняя полка слева', max_length=100, verbose_name='Позиция')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('display', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='geo.display', verbose_name='Витрина')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар на витрине',
                'verbose_name_plural': 'Товары на витринах',
                'unique_together': {('display', 'product')},
            },
        ),
        migrations.CreateModel(
            name='OutletInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='geo.outlet', verbose_name='Торговая точка')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Товар')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'Наличие товара',
                'verbose_name_plural': 'Наличие товаров',
                'unique_together': {('outlet', 'product')},
            },
        ),
    ]
