# Generated by Django 5.2.7 on 2025-12-04 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_display_footfallcounter_displayinventory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'ordering': ['district', 'name'], 'verbose_name': 'Канал сбыта', 'verbose_name_plural': 'Каналы сбыта'},
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('code', models.CharField(max_length=50, verbose_name='Код')),
                ('geo_polygon', models.JSONField(blank=True, null=True, verbose_name='Полигон (GeoJSON)')),
                ('data_type', models.CharField(choices=[('expert', 'Экспертный'), ('monitoring', 'Мониторинговый'), ('mixed', 'Смешанный')], default='mixed', max_length=20, verbose_name='Тип данных')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные настройки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='geo.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ['region', 'name'],
                'unique_together': {('region', 'code')},
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('code', models.CharField(max_length=50, verbose_name='Код')),
                ('geo_polygon', models.JSONField(blank=True, null=True, verbose_name='Полигон (GeoJSON)')),
                ('data_type', models.CharField(choices=[('expert', 'Экспертный'), ('monitoring', 'Мониторинговый'), ('mixed', 'Смешанный')], default='mixed', max_length=20, verbose_name='Тип данных')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные настройки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='geo.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Районы',
                'ordering': ['city', 'name'],
                'unique_together': {('city', 'code')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='channel',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='channel',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='geo.district', verbose_name='Район'),
        ),
        migrations.AlterUniqueTogether(
            name='channel',
            unique_together={('district', 'code')},
        ),
        migrations.RemoveField(
            model_name='channel',
            name='region',
        ),
    ]
