# Generated by Django 5.2.7 on 2025-12-04 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_alter_channel_options_city_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='geo.district', verbose_name='Район'),
        ),
    ]
