# Generated by Django 5.2.7 on 2025-12-05 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_alter_channel_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='geo.district', verbose_name='Район'),
        ),
    ]
